// Copy text to clipboard
export const copyToClipboard = (text) => {
  navigator.clipboard
    .writeText(text)
    .then(() => {
      alert("Summary copied to clipboard!")
    })
    .catch((err) => {
      console.error("Failed to copy text: ", err)
      alert("Failed to copy to clipboard")
    })
}

// Download summary as PDF file
export const downloadSummaryAsPDF = (htmlContent, filename) => {
  // Create a new window for PDF generation
  const printWindow = window.open("", "", "height=600,width=800")

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
        <title>${filename}</title>
        <style>
            body { 
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
                line-height: 1.6; 
                color: #333; 
                max-width: 800px; 
                margin: 0 auto; 
                padding: 20px;
                background: white;
            }
            h1, h2, h3 { 
                color: #2563eb; 
                margin-top: 1.5em;
                margin-bottom: 0.5em;
            }
            h1 { font-size: 24px; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
            h2 { font-size: 20px; }
            h3 { font-size: 18px; }
            h4 { font-size: 16px; color: #7c3aed; }
            p { margin: 10px 0; }
            strong { color: #dc2626; font-weight: 600; }
            em { color: #059669; }
            ul { margin: 10px 0; padding-left: 20px; }
            li { margin: 5px 0; }
            .header { text-align: center; margin-bottom: 30px; }
            .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280; text-align: center; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>AutoNotes Summary</h1>
            <p style="color: #6b7280;">Generated on ${new Date().toLocaleDateString()}</p>
        </div>
        ${htmlContent}
        <div class="footer">
            <p>Generated by AutoNotes - AI-Powered Video Summarization Tool</p>
        </div>
    </body>
    </html>
  `)

  printWindow.document.close()

  // Wait for content to load, then print as PDF
  printWindow.onload = function () {
    setTimeout(() => {
      printWindow.print()
      printWindow.close()
    }, 250)
  }
}

// Update localStorage with edited content
export const updateEditedContentInStorage = (editedHtmlContent) => {
  const recentItems = JSON.parse(
    localStorage.getItem("autoNotesSummaries") || "[]"
  )

  if (recentItems.length > 0) {
    // Update the most recent item with edited content
    recentItems[0].editedContent = editedHtmlContent
    recentItems[0].lastEdited = new Date().toISOString()
    localStorage.setItem("autoNotesSummaries", JSON.stringify(recentItems))
  }
}
